### ISSUE TITLE
Possibility to add translations

### ISSUE THREAD

**Issue by GeleiaComPepino** [Unkzittys/DokiDokiLiteratureClub_AndroidPort#2]
I am from Brazil and i need a translation, than, the translation is a mod, than is not compatible with the app

I need a translation because my English is bad and I can feel more immersive in game with the translation.

You can either add the translation options for all languages ​​or allow the addition of mod.

Please, I need this.

**Comment by Unkzittys** [comment]
Hello and thanks for your suggestion.

I've been planning to bring an update to add Portuguese and Spanish languages ​​for a while now, and I haven't done that yet because of some additions I'm planning to the base version. However I will make sure of bringing an update for these languages ​​as soon as possible (maybe in a day or two) since I'm not in a big rush to make the changes, so stay tuned!
